name: Code Check

on:
  pull_request:
    branches:
      - dev

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Replace this with your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Jest tests
        run: npm test